// Copyright 2026 The Afterbird Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/extensions/android/devtools_bridge.h"

#include <memory>
#include <utility>

#include "base/files/file_path.h"
#include "base/logging.h"
#include "base/strings/stringprintf.h"
#include "chrome/browser/profiles/profile.h"
#include "content/public/browser/devtools_agent_host.h"
#include "content/public/browser/devtools_socket_factory.h"
#include "content/public/browser/web_contents.h"
#include "net/base/ip_endpoint.h"
#include "net/base/net_errors.h"
#include "net/log/net_log_source.h"
#include "net/socket/tcp_server_socket.h"

// Generated by generate_jni in chrome/browser/extensions/android:jni_headers.
// Must come after all headers that specialize FromJniType() / ToJniType().
#include "chrome/browser/extensions/android/jni_headers/DevToolsBridge_jni.h"

using content::DevToolsAgentHost;

namespace extensions {

namespace {

constexpr int kBackLog = 10;
constexpr char kLoopback[] = "127.0.0.1";

// Lazily-initialised process-wide state. We intentionally leak this: the
// DevTools HTTP server is pinned to the process lifetime per user guidance
// ("once started, keep it running"), so there's no teardown path.
struct ServerState {
  bool attempted = false;
  uint16_t port = 0;
};

ServerState& GetState() {
  static ServerState* state = new ServerState();
  return *state;
}

// net::ServerSocket factory that binds to 127.0.0.1:0 and stashes the
// kernel-assigned port in ServerState so callers can build URLs.
class LoopbackTcpSocketFactory : public content::DevToolsSocketFactory {
 public:
  LoopbackTcpSocketFactory() = default;
  LoopbackTcpSocketFactory(const LoopbackTcpSocketFactory&) = delete;
  LoopbackTcpSocketFactory& operator=(const LoopbackTcpSocketFactory&) = delete;
  ~LoopbackTcpSocketFactory() override = default;

 private:
  // DevToolsSocketFactory:
  std::unique_ptr<net::ServerSocket> CreateForHttpServer() override {
    auto socket = std::make_unique<net::TCPServerSocket>(
        /*net_log=*/nullptr, net::NetLogSource());
    int rv =
        socket->ListenWithAddressAndPort(kLoopback, /*port=*/0, kBackLog);
    if (rv != net::OK) {
      LOG(ERROR) << "DevToolsBridge: failed to bind 127.0.0.1:0 rv=" << rv;
      return nullptr;
    }
    net::IPEndPoint endpoint;
    if (socket->GetLocalAddress(&endpoint) == net::OK) {
      GetState().port = endpoint.port();
      LOG(INFO) << "DevToolsBridge: listening on 127.0.0.1:" << endpoint.port();
    }
    return socket;
  }

  std::unique_ptr<net::ServerSocket> CreateForTethering(
      std::string* /*out_name*/) override {
    // Not supported — tethering (port-forwarding) is a desktop feature and is
    // not needed for on-device DevTools.
    return nullptr;
  }
};

}  // namespace

// static
uint16_t DevToolsBridge::EnsureServerStarted() {
  ServerState& state = GetState();
  if (state.attempted) {
    return state.port;
  }
  state.attempted = true;

  DevToolsAgentHost::StartRemoteDebuggingServer(
      std::make_unique<LoopbackTcpSocketFactory>(),
      /*active_port_output_directory=*/base::FilePath(),
      /*debug_frontend_dir=*/base::FilePath());

  // The factory's CreateForHttpServer() was called synchronously by
  // StartRemoteDebuggingServer, so port is now populated if bind succeeded.
  return state.port;
}

// static
std::string DevToolsBridge::BuildFrontendUrlFor(
    content::WebContents* web_contents) {
  if (!web_contents) {
    return std::string();
  }
  uint16_t port = EnsureServerStarted();
  if (port == 0) {
    return std::string();
  }

  scoped_refptr<DevToolsAgentHost> host =
      DevToolsAgentHost::GetOrCreateFor(web_contents);
  if (!host) {
    return std::string();
  }

  // The bundled frontend on Android is served at /devtools/inspector.html
  // (see content/browser/devtools/devtools_http_handler.cc
  //  GetFrontendURLInternal, when delegate_->HasBundledFrontendResources()
  //  is true). The ?ws= parameter wires it to the per-page WebSocket.
  return base::StringPrintf(
      "http://%s:%u/devtools/inspector.html?ws=%s:%u/devtools/page/%s",
      kLoopback, port, kLoopback, port, host->GetId().c_str());
}

// JNI entry point: Java passes (Profile*, WebContents*), but profile is
// unused here — DevToolsAgentHost is per-WebContents.
static std::string JNI_DevToolsBridge_Open(
    JNIEnv* env,
    Profile* /*profile*/,
    content::WebContents* web_contents) {
  return DevToolsBridge::BuildFrontendUrlFor(web_contents);
}

}  // namespace extensions
