// Copyright 2026 The Afterbird Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/extensions/android/extension_install_bridge.h"

#include <memory>
#include <utility>

#include "base/android/jni_string.h"
#include "base/files/file_path.h"
#include "base/logging.h"
#include "content/public/browser/web_contents.h"

// Generated by //chrome/browser/extensions/android:jni_headers.
#include "chrome/browser/extensions/android/jni_headers/ExtensionInstallBridge_jni.h"

namespace extensions {

// static
void ExtensionInstallCallback::Show(content::WebContents* web_contents,
                                    PickFileCallback cb) {
  if (!web_contents) {
    std::move(cb).Run(base::FilePath());
    return;
  }
  // Self-owned — deletes in OnFilePicked.
  auto* owned = new ExtensionInstallCallback(std::move(cb));
  JNIEnv* env = jni_zero::AttachCurrentThread();
  Java_ExtensionInstallBridge_showFilePicker(
      env, reinterpret_cast<jlong>(owned),
      web_contents->GetJavaWebContents());
}

ExtensionInstallCallback::ExtensionInstallCallback(PickFileCallback cb)
    : cb_(std::move(cb)) {}

ExtensionInstallCallback::~ExtensionInstallCallback() = default;

void ExtensionInstallCallback::OnFilePicked(
    JNIEnv* env,
    const jni_zero::JavaParamRef<jstring>& path) {
  std::string utf8 = base::android::ConvertJavaStringToUTF8(env, path);
  if (cb_) {
    std::move(cb_).Run(base::FilePath::FromUTF8Unsafe(utf8));
  }
  delete this;
}

}  // namespace extensions
