// Copyright 2026 The Afterbird Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/extensions/android/extension_install_bridge.h"

#include <memory>
#include <string>
#include <utility>

#include "base/android/jni_string.h"
#include "base/files/file_path.h"
#include "base/functional/bind.h"
#include "base/logging.h"
#include "base/no_destructor.h"
#include "base/sequence_checker.h"
#include "content/public/browser/web_contents.h"

// Generated by //chrome/browser/extensions/android:jni_headers.
#include "chrome/browser/extensions/android/jni_headers/ExtensionInstallBridge_jni.h"

namespace extensions::android {

namespace {

// Simple handle→callback map. We hand the address of the owned callback
// across to Java as a `long`. Because the Java picker fires at most once per
// request and we erase the entry in OnFilePicked, we don't need a Mutex —
// everything runs on the UI thread.
class CallbackRegistry {
 public:
  static CallbackRegistry& Get() {
    static base::NoDestructor<CallbackRegistry> instance;
    return *instance;
  }

  int64_t Store(PickFileCallback cb) {
    DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
    auto owned = std::make_unique<PickFileCallback>(std::move(cb));
    int64_t handle = reinterpret_cast<int64_t>(owned.get());
    map_[handle] = std::move(owned);
    return handle;
  }

  PickFileCallback Take(int64_t handle) {
    DCHECK_CALLED_ON_VALID_SEQUENCE(sequence_checker_);
    auto it = map_.find(handle);
    if (it == map_.end()) {
      return {};
    }
    PickFileCallback cb = std::move(*it->second);
    map_.erase(it);
    return cb;
  }

 private:
  std::map<int64_t, std::unique_ptr<PickFileCallback>> map_;
  SEQUENCE_CHECKER(sequence_checker_);
};

}  // namespace

void ShowFilePicker(content::WebContents* web_contents, PickFileCallback cb) {
  if (!web_contents) {
    std::move(cb).Run(base::FilePath());
    return;
  }
  int64_t handle = CallbackRegistry::Get().Store(std::move(cb));
  JNIEnv* env = jni_zero::AttachCurrentThread();
  Java_ExtensionInstallBridge_showFilePicker(
      env, handle, web_contents->GetJavaWebContents());
}

}  // namespace extensions::android

// JNI callback from Java once the picker returned (success or cancel).
// Running on the UI thread (Java uses AsyncTask to stream the URI off-UI,
// then posts back to UI to call this).
static void JNI_ExtensionInstallBridge_OnFilePicked(
    JNIEnv* env,
    jlong j_native_callback,
    const jni_zero::JavaParamRef<jstring>& j_path) {
  std::string path = jni_zero::ConvertJavaStringToUTF8(env, j_path);
  extensions::android::PickFileCallback cb =
      extensions::android::CallbackRegistry::Get().Take(j_native_callback);
  if (cb) {
    std::move(cb).Run(base::FilePath::FromUTF8Unsafe(path));
  }
}
