// Copyright 2026 The Afterbird Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "chrome/browser/extensions/android/extension_install_confirm_bridge.h"

#include <utility>

#include "base/android/jni_string.h"
#include "base/logging.h"
#include "content/public/browser/web_contents.h"

// Generated by //chrome/browser/extensions/android:jni_headers.
#include "chrome/browser/extensions/android/jni_headers/ExtensionInstallConfirmBridge_jni.h"

namespace extensions {

// static
void ExtensionInstallConfirmCallback::Show(
    content::WebContents* web_contents,
    const std::string& name,
    const std::string& version,
    const std::string& permissions,
    const std::string& source_label,
    ConfirmCallback cb) {
  if (!web_contents) {
    std::move(cb).Run(false);
    return;
  }
  // Self-owned — deletes in OnConfirmDecision.
  auto* owned = new ExtensionInstallConfirmCallback(std::move(cb));
  JNIEnv* env = jni_zero::AttachCurrentThread();
  Java_ExtensionInstallConfirmBridge_showConfirmDialog(
      env, reinterpret_cast<jlong>(owned),
      web_contents->GetJavaWebContents(),
      base::android::ConvertUTF8ToJavaString(env, name),
      base::android::ConvertUTF8ToJavaString(env, version),
      base::android::ConvertUTF8ToJavaString(env, permissions),
      base::android::ConvertUTF8ToJavaString(env, source_label));
}

ExtensionInstallConfirmCallback::ExtensionInstallConfirmCallback(
    ConfirmCallback cb)
    : cb_(std::move(cb)) {}

ExtensionInstallConfirmCallback::~ExtensionInstallConfirmCallback() = default;

void ExtensionInstallConfirmCallback::OnConfirmDecision(JNIEnv* env,
                                                        jboolean confirmed) {
  if (cb_) {
    std::move(cb_).Run(confirmed == JNI_TRUE);
  }
  delete this;
}

}  // namespace extensions
